# Generated by Django 2.2.5 on 2020-02-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity', models.CharField(max_length=120, verbose_name='Charity')),
                ('time', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=60)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Item')),
            ],
        ),
    ]
